In [1]:
import numpy as np

# <b> $$\text{Quiz2} $$</b>
Let us consider a two dimensional array $M$ with entries as follows
<img src="Quiz22.png">

1. Write a python code to create the array $M$.

In [6]:
M=np.array([[23,-3,7,1,22,20],[5,-6,70,9,-3,-2],[0,4,2.4,12,8,7],[2,10,-9,-4,5,20],[13,8,4,4,-2,5],[1,4,2,3,7,1]])

2. Write one line python code to slice the values of $M$ in the blue box.

In [7]:
M[:,2]

array([ 7. , 70. ,  2.4, -9. ,  4. ,  2. ])

3. Write one line python code to slice the values of $M$ in the red box.

In [9]:
M[0,3:5]

array([ 1., 22.])

4. Write one line python code to slice the values of $M$ in the green box.

In [14]:
M[4:6,4:6]

array([[-2.,  5.],
       [ 7.,  1.]])

5. Write one line python code to define an array $B$ with entries obtained by slicing the values of $M$ in the purple boxes.

In [25]:
B=M[2:5:2,:5:2]
B

array([[ 0. ,  2.4,  8. ],
       [13. ,  4. , -2. ]])

6. Write one line python code to display the shape of $B$.

In [24]:
B.shape

(2, 3)

7. Write one line python code to change of shape $B$.

In [33]:
B=B.reshape(3,-1)

array([[ 0. ,  2.4],
       [ 8. , 13. ],
       [ 4. , -2. ]])

8. Write one line python code to display the new shape of the matrix $B$.

In [34]:
B.shape

(3, 2)